Traceback (most recent call last):
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/isaacflath/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig,ax = plt.subplots(figsize=(6,6))

model_h0 = bind(run_random,buy_chance=buy_chance,short_chance=short_chance,hold_time=28)
model_h1 = bind(run_model,n_periods=28,threshold=0.08,hold_time=28)
    
runs, ss = 200,100
h0 = run_bootstrap_test(valid,model_h0,model_h1,runs=runs,sample_size=ss)
ax.set_xlim(-.15,.15)

ax.hist(h0,alpha=0.5,bins=60,label = 'h0',range=(-.15,.15))
# ax.hist(h1,alpha=0.5,bins=60,label = 'h1',range=(-.15,.15))
x = calculate_returns(model_h1(valid),valid)
ax.scatter(x=x,y=0,marker="P",color='red',s=300)

title_r1 = f"h0 mean={np.array(h0).mean():.3f}\n"
title_r2 = f"h1 mean={np.array(h1).mean():.3f}"

ax.set_title(title_r1 + title_r2)
ax.legend(loc ='upper left') 
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [42][0m, in [0;36m<cell line: 16>[0;34m()[0m
[1;32m     13[0m ax[38;5;241m.[39mscatter(x[38;5;241m=[39mx,y[38;5;241m=[39m[38;5;241m0[39m,marker[38;5;241m=[39m[38;5;124m"[39m[38;5;124mP[39m[38;5;124m"[39m,color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mred[39m[38;5;124m'[39m,s[38;5;241m=[39m[38;5;241m300[39m)
[1;32m     15[0m title_r1 [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124mh0 mean=[39m[38;5;132;01m{[39;00mnp[38;5;241m.[39marray(h0)[38;5;241m.[39mmean()[38;5;132;01m:[39;00m[38;5;124m.3f[39m[38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[0;32m---> 16[0m title_r2 [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124mh1 mean=[39m[38;5;132;01m{[39;00mnp[38;5;241m.[39marray(h1)[38;5;241m.[39mmean()[38;5;132;01m:[39;00m[38;5;124m.3f[39m[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m     18[0m ax[38;5;241m.[39mset_title(title_r1 [38;5;241m+[39m title_r2)
[1;32m     19[0m ax[38;5;241m.[39mlegend(loc [38;5;241m=[39m[38;5;124m'[39m[38;5;124mupper left[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'h1' is not defined
NameError: name 'h1' is not defined

